blank_issues_enabled: true
contact_links:
  - name: ğŸ“‘ Documentation
    url: https://github.com/SparkBotDev/SparkBot-Development/wiki
    about: "New to Sparkâš¡ï¸Bot? Starting something new? Check out the wiki documentation."
  - name: ğŸ’¬ Join the Discord Community
    url: https://discord.gg/8ptjPttjvt
    about: "Chat about Sparkâš¡ï¸Bot and get help with your project."